name: Test pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  TEST:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Test Application
        run: |
          yarn run ci
          yarn run test:badge

      - name: Update README.md test coverage section
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[TEST] update test coverage'
          commit_user_name: eeeasycode
          commit_user_email: eeeasycode@gmail.com

          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: README.md
          repository: .
